name: pingou
  
channels:
  - conda-forge
  - defaults

dependencies:
 - python=3.8
 - asyncpg=0.21.0
 - rich=9.6.0
 - pyyaml=5.3.1
 - geoip2=4.0.2
 - ujson=4.0.2
 # Tests
 - pytest=6.2.1
 - psycopg2=2.8.5
 - pytest-cov=2.11.1
 - requests
